### ISSUE TITLE
The button that reads "Test" does not cause any action to appear on the screen

### ISSUE THREAD

**Issue by Nibbl-z** [FireEntity1/fireentity1.github.io#3]
### Subject of the issue
When I use the left click button on my mouse to activate the button, nothing happens.

### Your environment
* Google Chrome

### Steps to reproduce
1. Move the mouse cursor to have it located on the button that reads "Test"
2. Use the Left mouse button on the mouse to click the button
3. Nothing will happen afterwards

### Expected behaviour
Something really cool and awesome on Fireentity1.github.io

### Actual behaviour
There isn't a single action that appears on my screen. I need an instant dopamine hit when I click on the button. I am dissapointed and will be rating Fireentity1.github.io 1 Star on Yelp. Please try harder next time

**Comment by Nibbl-z** [comment]
Please FireEntity1, fix this.

**Comment by FireEntity1** [comment]
Hi Nibble-z. I will fix this soon, as I intend to add functionality to this site. Please sit tight!
